inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
