name: "[CI] app"

on:
  push:
    branches:
      - main
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 2.7.5
  NODE_VERSION: 16.9.1

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]
    env:
      DB_TEST_DATABASE: app-test
      DB_DATABASE: app
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      SECRET_KEY_BASE: "secret_key_base"

    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-app-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-app-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-app-rubydeps-

      - name: Set bundle local config vendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install
      - run: bundle exec rake db:test:prepare
        name: Setup database
      - run: bundle exec rspec
        name: Run specs
