name: "[CI] decidim_via_oberta_authorization"

on:
  push:
    branches:
      - main
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 3.0.1
  NODE_VERSION: 16.9.1

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-app-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-app-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-app-rubydeps-

      - name: Set bundle local config vendor/bundle path
        run: cd decidim-via_oberta_authorization && bundle config set --local path 'vendor/bundle'

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: cd decidim-via_oberta_authorization && bundle install --jobs 4 --retry 3

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Build module
        run: |
          cd decidim-via_oberta_authorization
          bundle exec rake decidim:generate_external_test_app
          cd spec/decidim_dummy_app/
          bundle exec rake decidim_via_oberta_authorization:install:migrations
          RAILS_ENV=test bundle exec rails db:migrate
      - name: Run specs
        run: cd decidim-via_oberta_authorization && bundle exec rspec
